const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Config plugin to auto-generate android/local.properties with SDK path
 * Also updates gradle.properties with Java home path (required for Windows)
 * Detects SDK location from environment or common paths
 */

const getJavaHomePath = () => {
  // Check environment variable first
  if (process.env.JAVA_HOME) {
    return process.env.JAVA_HOME;
  }

  const platform = process.platform;

  const possiblePaths = [];

  if (platform === 'win32') {
    possiblePaths.push(
      // Android Studio bundled JBR (recommended)
      'C:\\Program Files\\Android\\Android Studio\\jbr',
      'C:\\Program Files (x86)\\Android\\Android Studio\\jbr',
      // JDK installations
      'C:\\Program Files\\Java\\jdk-17',
      'C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.9.9-hotspot',
      'C:\\Program Files\\Microsoft\\jdk-17.0.9.8-hotspot'
    );
  } else if (platform === 'darwin') {
    possiblePaths.push(
      '/Applications/Android Studio.app/Contents/jbr/Contents/Home',
      '/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home',
      '/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home'
    );
  } else {
    // Linux
    possiblePaths.push(
      '/usr/lib/jvm/java-17-openjdk',
      '/usr/lib/jvm/java-17-openjdk-amd64'
    );
  }

  // Find first existing path
  for (const javaPath of possiblePaths) {
    if (fs.existsSync(javaPath)) {
      return javaPath;
    }
  }

  return null;
};

const getAndroidSdkPath = () => {
  // Check environment variables first
  if (process.env.ANDROID_HOME) {
    return process.env.ANDROID_HOME;
  }
  if (process.env.ANDROID_SDK_ROOT) {
    return process.env.ANDROID_SDK_ROOT;
  }

  // Platform-specific default paths
  const platform = process.platform;
  const home = process.env.HOME || process.env.USERPROFILE;

  const possiblePaths = [];

  if (platform === 'win32') {
    possiblePaths.push(
      path.join(process.env.LOCALAPPDATA || '', 'Android', 'Sdk'),
      path.join(home, 'AppData', 'Local', 'Android', 'Sdk'),
      'C:\\Android\\Sdk',
      'D:\\Android\\Sdk'
    );
  } else if (platform === 'darwin') {
    possiblePaths.push(
      path.join(home, 'Library', 'Android', 'sdk'),
      '/usr/local/share/android-sdk'
    );
  } else {
    // Linux
    possiblePaths.push(
      path.join(home, 'Android', 'Sdk'),
      '/opt/android-sdk',
      '/usr/local/android-sdk'
    );
  }

  // Find first existing path
  for (const sdkPath of possiblePaths) {
    if (fs.existsSync(sdkPath)) {
      return sdkPath;
    }
  }

  return null;
};

const withAndroidLocalProperties = (config) => {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const androidPath = config.modRequest.platformProjectRoot;
      const localPropertiesPath = path.join(androidPath, 'local.properties');
      const gradlePropertiesPath = path.join(androidPath, 'gradle.properties');

      // Generate local.properties with SDK path
      const sdkPath = getAndroidSdkPath();

      if (!sdkPath) {
        console.warn('⚠️  [Android] Could not detect Android SDK path. Please set ANDROID_HOME environment variable.');
        return config;
      }

      // Escape backslashes for Windows paths in properties file
      const escapedSdkPath = sdkPath.replace(/\\/g, '\\\\');

      const content = `# Auto-generated by withAndroidLocalProperties.js
# SDK path detected from environment or common locations
sdk.dir=${escapedSdkPath}
`;

      fs.writeFileSync(localPropertiesPath, content);
      console.log(`✅ [Android] Generated local.properties with SDK path: ${sdkPath}`);

      // Update gradle.properties with Java home path (Windows only)
      if (process.platform === 'win32') {
        const javaHome = getJavaHomePath();

        if (javaHome && fs.existsSync(gradlePropertiesPath)) {
          let gradlePropertiesContent = fs.readFileSync(gradlePropertiesPath, 'utf8');

          // Check if org.gradle.java.home is already set
          if (!gradlePropertiesContent.includes('org.gradle.java.home=')) {
            const escapedJavaHome = javaHome.replace(/\\/g, '\\\\');
            gradlePropertiesContent += `\n# Java home path (auto-detected by withAndroidLocalProperties.js)\norg.gradle.java.home=${escapedJavaHome}\n`;
            fs.writeFileSync(gradlePropertiesPath, gradlePropertiesContent);
            console.log(`✅ [Android] Added Java home to gradle.properties: ${javaHome}`);
          }
        } else if (!javaHome) {
          console.warn('⚠️  [Android] Could not detect Java home path. You may need to set JAVA_HOME or add org.gradle.java.home to gradle.properties.');
        }
      }

      return config;
    },
  ]);
};

module.exports = withAndroidLocalProperties;
